services:

  builder:
    build:
      context: .
      dockerfile: ./docker/composer/Dockerfile
      args:
        PACKAGE_NAME: ${PACKAGE_NAME:?error}
    volumes:
      - laravel:/app

    develop:
      watch:
        - path: ./package
          action: sync+restart
          target: /package

#  tester:
#    image:
#
#    depends_on:
#      builder:
#        condition: service_completed_successfully

  franken:
    image: dunglas/frankenphp
    ports:
      - 443:443
      - 80:80

    volumes:
      - laravel:/app

    depends_on:
      builder:
        condition: service_completed_successfully



volumes:
  laravel:
